require 'active_support/core_ext/array'
require 'active_support/core_ext/class'
require 'active_support/core_ext/hash'
require 'active_support/core_ext/integer'
require 'active_support/core_ext/module'
require 'active_support/core_ext/numeric'
require 'active_support/core_ext/object'
require 'active_support/core_ext/range'
require 'active_support/core_ext/string'
require 'active_support/core_ext/time'
require 'active_support/core_ext/enumerable'

require 'active_support/core_ext/kernel/singleton_class'
require 'active_support/core_ext/regexp'
